### ISSUE TITLE
Feature Request: Automatic From/TryFrom implementions for borrowed subenum values (references)

### ISSUE THREAD

**Issue by DavidAntliff** [paholg/subenum#35]
I might have missed this if it already works, but in case I haven't, would it be possible to have automatic `From` and `TryFrom` implementations for _borrowed_ subenums please?

For example, if we have:

```rust
    #[subenum(MyEnum)]
    enum BaseEnum {
        #[subenum(MyEnum)]
        A,
    }

    let e = MyEnum::A;
    let f = &e;

    let g = BaseEnum::from(f);
```
```
error[E0277]: the trait bound `BaseEnum: From<&MyEnum>` is not satisfied
   --> src/main.rs:10:13
    |
132 |     let g = BaseEnum::from(f);
    |             ^^^^^^^^ the trait `From<&MyEnum>` is not implemented for `BaseEnum`
    |
    = help: the trait `From<MyEnum>` is implemented for `BaseEnum`
    = help: for that trait implementation, expected `MyEnum`, found `&MyEnum`
```

The workaround is to deref the borrowed enum and clone, but that could be expensive with larger enum variants:

```rust
    #[subenum(MyEnum)]
    #[derive(Clone)]
    enum BaseEnum {
        #[subenum(MyEnum)]
        A,
    }

    // ...

    let g = BaseEnum::from((*f).clone());
```

**Comment by paholg** [comment]
How would one implement this without cloning the variant?

**Comment by DavidAntliff** [comment]
I think it _would_ clone the variant, but it would do it inside the automatic From/TryFrom implementation - but is that not a good idea?

Is it better in terms of API design to have the clone performed explicitly by the caller?

Perhaps since there's no special behaviour required within the From/TryFrom implementation it does make sense to keep the cloning explicit.

Question: for a simple enum, no struct/tuple "payload", does calling `BaseEnum::from((*f).clone())` do two clones? One to make a copy of the source enum, and then the actual `from()` implementation makes a new copy as a `BaseEnum`? Or does it just convert the type in-place?

**Comment by paholg** [comment]
My preference is to keep cloning explicit. Otherwise, it's too easy to accidentally clone when calling `into()` on a reference. 

I imagine the compiler is able to optimize away the double-clone in your example, though I can't say for sure.

**Comment by DavidAntliff** [comment]
Fair enough, it makes sense to keep things explicit. I'll close this.
